### ISSUE TITLE
certbot-dns-pdns is broken on certbot-dns-lexicon 3.17.0

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [kaechele/certbot-dns-pdns#85]
The API ostensibly changed, because now my challenges fail while the pDNS plugin is trying to use dns-lexicon:

```
 211   │ 2024-11-07 19:15:28,548:INFO:certbot._internal.auth_handler:Performing the following challenges:
 212   │ 2024-11-07 19:15:28,548:INFO:certbot._internal.auth_handler:dns-01 challenge for filmroellchen.eu
 213   │ 2024-11-07 19:15:28,548:INFO:certbot._internal.auth_handler:dns-01 challenge for filmroellchen.eu
 214   │ 2024-11-07 19:15:28,555:DEBUG:certbot._internal.error_handler:Encountered exception:
 215   │ Traceback (most recent call last):
 216   │   File "/usr/lib/python3.12/site-packages/certbot/plugins/dns_common_lexicon.py", line 250, in _resolve_domain
 217   │     with Client(self._build_lexicon_config(domain_name)):
 218   │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 219   │   File "/usr/lib/python3.12/site-packages/certbot/plugins/dns_common_lexicon.py", line 210, in _build_lexicon_config
 220   │     return ConfigResolver().with_dict(dict_config).with_env()
 221   │            ^^^^^^^^^^^^^^^^
 222   │ TypeError: 'NoneType' object is not callable
 223   │
```

Probably the same (or related) error: [#9982](https://github.com/certbot/certbot/issues/9982)

**Comment by kaechele** [comment]
Thanks for reporting! Looks like a bug in certbot / dns-lexicon.
Also an odd one. I can't reproduce it in isolation (in a venv). So I'm assuming there may be some dependency versioning / pinning issue at play. I will need to investigate further.
